param(
  [string]$FixtureDirectory = "testdata/uritemplate-test",
  [string]$OutputPath = "conformance_generated_wbtest.mbt",
  [string]$SummaryPath = "conformance-summary.json"
)

$ErrorActionPreference = "Stop"
$invariant = [Globalization.CultureInfo]::InvariantCulture

function Quote-MoonString([string]$Value) {
  if ($null -eq $Value) {
    return '""'
  }
  $escaped = $Value.Replace('\', '\\')
  $escaped = $escaped.Replace('"', '\"')
  $escaped = $escaped.Replace("`r", '\r')
  $escaped = $escaped.Replace("`n", '\n')
  $escaped = $escaped.Replace("`t", '\t')
  return '"' + $escaped + '"'
}

function Scalar-Text($Value) {
  if ($Value -is [string]) {
    return $Value
  }
  if ($Value -is [IFormattable]) {
    return $Value.ToString($null, $invariant)
  }
  return [string]$Value
}

function Uri-Value-Expression($Value) {
  if ($Value -is [string] -or $Value -is [ValueType]) {
    return "Scalar($(Quote-MoonString (Scalar-Text $Value)))"
  }
  if ($Value -is [array]) {
    $members = @($Value | ForEach-Object {
      Quote-MoonString (Scalar-Text $_)
    })
    return "List([" + ($members -join ", ") + "])"
  }
  if ($Value -is [PSCustomObject]) {
    $members = @($Value.PSObject.Properties | ForEach-Object {
      "(" + (Quote-MoonString $_.Name) + ", " +
        (Quote-MoonString (Scalar-Text $_.Value)) + ")"
    })
    return "Assoc([" + ($members -join ", ") + "])"
  }
  throw "Unsupported fixture value type: $($Value.GetType().FullName)"
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add("// Generated by tools/generate_conformance_tests.ps1.")
$lines.Add("// Source attribution is recorded in THIRD_PARTY.md.")
$lines.Add("")
$lines.Add("///|")
$lines.Add("fn conformance_rejects(")
$lines.Add("  template : String,")
$lines.Add("  variables : Map[String, UriValue],")
$lines.Add(") -> Bool {")
$lines.Add("  UriTemplate::parse(template) catch {")
$lines.Add("    _ => true")
$lines.Add("  } noraise {")
$lines.Add("    parsed =>")
$lines.Add("      parsed.expand(variables) catch {")
$lines.Add("        _ => true")
$lines.Add("      } noraise {")
$lines.Add("        _ => false")
$lines.Add("      }")
$lines.Add("  }")
$lines.Add("}")
$lines.Add("")

$fixtureNames = @(
  "spec-examples.json",
  "extended-tests.json",
  "negative-tests.json"
)
$testNumber = 0
$rejectionCount = 0
$fixtureSummary = [ordered]@{}

foreach ($fixtureName in $fixtureNames) {
  $fixtureTestCount = 0
  $fixtureRejectionCount = 0
  $fixturePath = Join-Path $FixtureDirectory $fixtureName
  $document = Get-Content -Raw -LiteralPath $fixturePath | ConvertFrom-Json
  foreach ($groupProperty in $document.PSObject.Properties) {
    $group = $groupProperty.Value
    foreach ($case in $group.testcases) {
      $testNumber += 1
      $fixtureTestCount += 1
      $template = [string]$case[0]
      $expected = $case[1]
      $testName = "conformance $fixtureName #$testNumber"
      $lines.Add("///|")
      $lines.Add("test $(Quote-MoonString $testName) {")
      $lines.Add("  let variables : Map[String, UriValue] = {")
      foreach ($variable in $group.variables.PSObject.Properties) {
        if ($null -ne $variable.Value) {
          $lines.Add(
            "    " + (Quote-MoonString $variable.Name) + ": " +
            (Uri-Value-Expression $variable.Value) + ","
          )
        }
      }
      $lines.Add("  }")
      if ($expected -is [bool] -and -not $expected) {
        $rejectionCount += 1
        $fixtureRejectionCount += 1
        $lines.Add(
          "  assert_true(conformance_rejects(" +
          (Quote-MoonString $template) + ", variables))"
        )
      } else {
        $expectedValues = if ($expected -is [array]) {
          @($expected)
        } else {
          @($expected)
        }
        $expectedExpression = @($expectedValues | ForEach-Object {
          Quote-MoonString ([string]$_)
        }) -join ", "
        $lines.Add(
          "  let parsed = UriTemplate::parse(" +
          (Quote-MoonString $template) + ")"
        )
        $lines.Add("  let actual = parsed.expand(variables)")
        $lines.Add("  let expected = [$expectedExpression]")
        $lines.Add("  if !expected.contains(actual) {")
        $lines.Add(
          "    fail(" +
          (Quote-MoonString "$fixtureName expected a permitted expansion") +
          " + `": \{actual}`")"
        )
        $lines.Add("  }")
      }
      $lines.Add("}")
      $lines.Add("")
    }
  }
  $fixtureSummary[$fixtureName] = [ordered]@{
    tests = $fixtureTestCount
    expected_rejections = $fixtureRejectionCount
  }
}

$absoluteOutput = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath))
$workspace = [IO.Path]::GetFullPath((Get-Location).Path)
if (-not $absoluteOutput.StartsWith($workspace + [IO.Path]::DirectorySeparatorChar)) {
  throw "Refusing to write generated tests outside the workspace: $absoluteOutput"
}

$encoding = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllLines($absoluteOutput, $lines, $encoding)

$absoluteSummary = [IO.Path]::GetFullPath(
  (Join-Path (Get-Location) $SummaryPath)
)
if (-not $absoluteSummary.StartsWith(
    $workspace + [IO.Path]::DirectorySeparatorChar
  )) {
  throw "Refusing to write summary outside the workspace: $absoluteSummary"
}
$summary = [ordered]@{
  schema_version = 1
  standard = "RFC 6570"
  supported_level = 4
  upstream_repository = "https://github.com/uri-templates/uritemplate-test"
  upstream_commit = "4171dac22aa67fc710b3f6df308a50bd08552986"
  generated_tests = $testNumber
  expected_rejections = $rejectionCount
  fixtures = $fixtureSummary
}
$summaryJson = $summary | ConvertTo-Json -Depth 5
[IO.File]::WriteAllText(
  $absoluteSummary,
  $summaryJson + [Environment]::NewLine,
  $encoding
)
Write-Output (
  "Generated $testNumber conformance tests and summary at " +
  "$absoluteOutput and $absoluteSummary"
)
